spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/totoro?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: select 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: TotoroHikariCP
  # redis
  redis:
    host: 127.0.0.1
    database: 8
    port: 6379
    timeout: 3000
  # mail
  mail:
    host: smtp.163.com
    username: dengmiao1002@163.com
    password: dengmiao1002