# 项目其他配置
totoro:
  project:
    name: Totoro
    version: 1.0.0M1
    poweredBy: dengmiao
  upload:
    # 文件上传目录
    path: E://upFiles/totoro
  security:
    # 登录页
    login-page: /security/needLogin
    # 登入
    login-url: /login
    # 登出
    logout-url: /logout
    # 忽略鉴权
    ignoreUrls:
      - /test/**
      - /druid/**
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.jpg
      - /**/*.ico
    # token失效时间(分钟)
    tokenExpireTime: 60
  #swagger
  swagger2:
    enable: true
    base-package: com.cn.miao
    title: ${totoro.project.name}
    description: ${totoro.project.name} Restful API docs
    termsOfServiceUrl: http://localhost:${server.port}
    version: ${totoro.project.version}
    apiName: Authorization
    apiKeyName: Authorization
  # 短信配置
  sms:
    type: aliyun
    aliyun:
      access-key-id: asdf
      access-key-secret: @@@