server:
  port: 8012
  servlet:
    context-path: /totoro

spring:
  profiles:
    active:
      - dev
      - edged
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

jasypt:
  encryptor:
    password: totoro